version: "3.3"

services:
  db:
    image: mysql:5.7.30
    container_name: hangout-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hangout
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - "./data:/var/lib/mysql"
  api:
    build: .
    container_name: gallery-api
    environment:
      MODE: "prod"
      DB_URL: "root:password@tcp(db:3306)/hangout?parseTime=true"
      HMAC_KEY: "secret"
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./upload:/app/upload"
